__author__ = 'Marco'

class responseCode:

    # return types
    ELEM_TYPE_ERROR = 0
    CREATE_ELEM_SUCCESS = 1
    ELEM_ALREADY_EXIST = 2
    ELEM_NOT_EXIST = 3
    UPDATE_ELEM_SUCCESS = 4
    GET_ELEM_SUCCESS = 5
    ELEM_INCR_SUCCESS = 6
    ELEM_DECR_SUCCESS = 7
    ELEM_SEARCH_SUCCESS = 8
    DB_SAVE_ERROR = 9
    DB_SAVE_SUCCESS = 10
    ELEM_IS_LOCKED = 11
    DB_SAVE_LOCKED = 12
    ELEM_DELETE_SUCCESS = 13
    DB_EXISTED = 14
    DB_CREATE_SUCCESS = 15
    DB_GET_SUCCESS = 16
    CREATE_LIST_SUCCESS = 17
    LIST_ALREADY_EXIST = 18
    LIST_IS_LOCKED = 19
    LIST_INSERT_SUCCESS = 20
    LIST_NOT_CONTAIN_VALUE = 21
    LIST_REMOVE_SUCCESS = 22
    LIST_NOT_EXIST = 23
    LIST_SEARCH_SUCCESS = 24
    GET_LIST_SUCCESS = 25
    LIST_DELETE_SUCCESS = 26
    DB_DELETE_SUCCESS = 27
    DB_NOT_EXIST = 28
